/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reversibledatahidingserver;

import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import com.reversible.ConsoleRedirect;
import com.reversible.Globals;
import com.reversible.algorithms.TransformationAlgortihms;
import com.reversibledata.db.DBUtils;
import com.reversibledata.model.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.table.AbstractTableModel;
import reversibledatahidingserver.server.ServerThread;

/**
 *
 * @author Santhosh
 */
public class ReversibleDataHidingServerMain extends javax.swing.JFrame {

    /**
     * Creates new form ReversibleDataHidingServerMain
     */
    public ReversibleDataHidingServerMain() {
        initComponents();
        
        ConsoleRedirect redirect = new ConsoleRedirect(this.jTextPaneConsole, this.jProgressBarProgress, System.out);
        System.setOut(redirect);
        System.setErr(redirect);
        
        System.out.println("!!Welcome To Reversible Data Hiding!!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jInternalFrameConsole = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneConsole = new javax.swing.JTextPane();
        jProgressBarProgress = new javax.swing.JProgressBar();
        jInternalFrameImageDatabase = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableImageDatabase = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButtonSelectSourceImage = new javax.swing.JButton();
        jButtonSelectTargetImage = new javax.swing.JButton();
        jButtonTransformAndSend = new javax.swing.JButton();
        jInternalFrameSourceImage = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabelSourceImage = new javax.swing.JLabel();
        jInternalFrameTargetImage = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabelTargetImage = new javax.swing.JLabel();
        jInternalFrameTransformedImage = new javax.swing.JInternalFrame();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jLabelTransformedImage = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItemStartServer = new javax.swing.JMenuItem();
        jMenuItemTransformImages = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REVERSIBLE DATA HIDING");

        desktopPane.setBackground(new java.awt.Color(51, 51, 255));
        desktopPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jInternalFrameConsole.setClosable(true);
        jInternalFrameConsole.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameConsole.setIconifiable(true);
        jInternalFrameConsole.setMaximizable(true);
        jInternalFrameConsole.setResizable(true);
        jInternalFrameConsole.setTitle("Console Output");
        jInternalFrameConsole.setToolTipText("");
        jInternalFrameConsole.setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextPaneConsole.setBackground(new java.awt.Color(0, 51, 0));
        jTextPaneConsole.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSOLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 18), new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createEtchedBorder())); // NOI18N
        jTextPaneConsole.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jTextPaneConsole.setForeground(new java.awt.Color(102, 204, 0));
        jScrollPane1.setViewportView(jTextPaneConsole);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jInternalFrameConsole.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jProgressBarProgress.setPreferredSize(new java.awt.Dimension(146, 22));
        jInternalFrameConsole.getContentPane().add(jProgressBarProgress, java.awt.BorderLayout.PAGE_START);

        desktopPane.add(jInternalFrameConsole);
        jInternalFrameConsole.setBounds(100, 70, 630, 280);

        jInternalFrameImageDatabase.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameImageDatabase.setIconifiable(true);
        jInternalFrameImageDatabase.setMaximizable(true);
        jInternalFrameImageDatabase.setResizable(true);
        jInternalFrameImageDatabase.setTitle("Image Database");
        jInternalFrameImageDatabase.setVisible(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Images", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 14), new java.awt.Color(102, 153, 255))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTableImageDatabase.setBackground(new java.awt.Color(51, 153, 255));
        jTableImageDatabase.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTableImageDatabase.setForeground(new java.awt.Color(51, 51, 51));
        jTableImageDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableImageDatabase.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(jTableImageDatabase);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setPreferredSize(new java.awt.Dimension(10, 100));

        jButtonSelectSourceImage.setText("SELECT SOURCE IMAGE");
        jButtonSelectSourceImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectSourceImageActionPerformed(evt);
            }
        });

        jButtonSelectTargetImage.setText("SELECT TARGET IMAGE");
        jButtonSelectTargetImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectTargetImageActionPerformed(evt);
            }
        });

        jButtonTransformAndSend.setText("TRANSFORM AND SEND");
        jButtonTransformAndSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransformAndSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButtonSelectSourceImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelectTargetImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButtonTransformAndSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(82, 82, 82)))
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSelectSourceImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSelectTargetImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTransformAndSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jInternalFrameImageDatabase.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        desktopPane.add(jInternalFrameImageDatabase);
        jInternalFrameImageDatabase.setBounds(100, 360, 510, 360);

        jInternalFrameSourceImage.setClosable(true);
        jInternalFrameSourceImage.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameSourceImage.setIconifiable(true);
        jInternalFrameSourceImage.setMaximizable(true);
        jInternalFrameSourceImage.setResizable(true);
        jInternalFrameSourceImage.setTitle("Source Image");
        jInternalFrameSourceImage.setVisible(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Source Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 14), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setViewportView(jLabelSourceImage);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jInternalFrameSourceImage.getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        desktopPane.add(jInternalFrameSourceImage);
        jInternalFrameSourceImage.setBounds(100, 360, 410, 370);

        jInternalFrameTargetImage.setClosable(true);
        jInternalFrameTargetImage.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameTargetImage.setIconifiable(true);
        jInternalFrameTargetImage.setMaximizable(true);
        jInternalFrameTargetImage.setResizable(true);
        jInternalFrameTargetImage.setTitle("Target Image");
        jInternalFrameTargetImage.setVisible(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Target Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 14), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setViewportView(jLabelTargetImage);

        jPanel6.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jInternalFrameTargetImage.getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        desktopPane.add(jInternalFrameTargetImage);
        jInternalFrameTargetImage.setBounds(520, 360, 410, 370);

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        jInternalFrameTransformedImage.setClosable(true);
        jInternalFrameTransformedImage.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameTransformedImage.setIconifiable(true);
        jInternalFrameTransformedImage.setMaximizable(true);
        jInternalFrameTransformedImage.setResizable(true);
        jInternalFrameTransformedImage.setTitle("Transformed Image");
        jInternalFrameTransformedImage.setVisible(false);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Transformed Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 14), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel7.setLayout(new java.awt.BorderLayout());

        jScrollPane5.setViewportView(jLabelTransformedImage);

        jPanel7.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jInternalFrameTransformedImage.getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jInternalFrameTransformedImage, java.awt.BorderLayout.PAGE_START);

        menuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Reversible Data");

        jMenuItemStartServer.setText("Start Server...");
        jMenuItemStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStartServerActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemStartServer);

        jMenuItemTransformImages.setText("Transform Images...");
        jMenuItemTransformImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransformImagesActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemTransformImages);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private ServerThread serverThread;
    
    private void jMenuItemStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStartServerActionPerformed
        
        if(this.serverThread==null) {
            final ServerThread serverThread = new ServerThread();
            serverThread.start();

            this.serverThread = serverThread;
            
            this.jMenuItemStartServer.setEnabled(false);
        }
        
    }//GEN-LAST:event_jMenuItemStartServerActionPerformed

    private void jMenuItemTransformImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransformImagesActionPerformed
        
        try {
            refreshImageDatabase();
            
            this.jInternalFrameImageDatabase.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ReversibleDataHidingServerMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItemTransformImagesActionPerformed

    private void refreshImageDatabase() throws Exception {
        DBUtils.connect();
        final List<Image> images = DBUtils.getImages();

        final List<String[]> imageDatabase = images.stream().map(i->new String[] { ""+i.getimageid(),i.getimagefile(),i.getimagetype() }).collect(Collectors.toList());
        
        this.jTableImageDatabase.setModel(new AbstractTableModel() {
            private String[] columns = new String[] { "Image ID","File Name","Image Type" };
            
            @Override
            public int getRowCount() {
                return imageDatabase.size();
            }

            @Override
            public int getColumnCount() {
                return this.columns.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                return imageDatabase.get(rowIndex)[columnIndex];
            }

            @Override
            public String getColumnName(int column) {
                return this.columns[column];
            }
            
        });
        
        this.jTableImageDatabase.invalidate();
        this.jTableImageDatabase.updateUI();
    }
    
    private void jButtonSelectSourceImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectSourceImageActionPerformed
        
        try {
            int row = this.jTableImageDatabase.getSelectedRow();
            
            final String sourceFile = this.jTableImageDatabase.getModel().getValueAt(row, 1).toString();
            
            final File sourcePath = new File(Globals.DATA_REPOSITORY,sourceFile);
            
            final BufferedImage sourceImage = ImageIO.read(sourcePath);
            
            final BufferedImage resizedImage = Globals.resizeImage(sourceImage, 512, 512);
            
            this.jLabelSourceImage.setIcon(new ImageIcon(resizedImage));
            
            this.jInternalFrameSourceImage.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ReversibleDataHidingServerMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonSelectSourceImageActionPerformed

    private void jButtonSelectTargetImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectTargetImageActionPerformed
        
        try {
            int row = this.jTableImageDatabase.getSelectedRow();
            
            final String targetFile = this.jTableImageDatabase.getModel().getValueAt(row, 1).toString();
            
            final File targetPath = new File(Globals.DATA_REPOSITORY,targetFile);
            
            final BufferedImage targetImage = ImageIO.read(targetPath);
            
            final BufferedImage resizedImage = Globals.resizeImage(targetImage, 512, 512);
            
            this.jLabelTargetImage.setIcon(new ImageIcon(resizedImage));
            
            this.jInternalFrameTargetImage.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ReversibleDataHidingServerMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jButtonSelectTargetImageActionPerformed

    private void jButtonTransformAndSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransformAndSendActionPerformed
        
        final BufferedImage tranformedImage = TransformationAlgortihms.createTranformedImage(
                (BufferedImage) ((ImageIcon)this.jLabelSourceImage.getIcon()).getImage()
                ,(BufferedImage) ((ImageIcon)this.jLabelTargetImage.getIcon()).getImage());
        
        
        this.jLabelTransformedImage.setIcon(new ImageIcon(tranformedImage));
        
        this.jInternalFrameTransformedImage.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jButtonTransformAndSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new HiFiLookAndFeel());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReversibleDataHidingServerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReversibleDataHidingServerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButtonSelectSourceImage;
    private javax.swing.JButton jButtonSelectTargetImage;
    private javax.swing.JButton jButtonTransformAndSend;
    private javax.swing.JInternalFrame jInternalFrameConsole;
    private javax.swing.JInternalFrame jInternalFrameImageDatabase;
    private javax.swing.JInternalFrame jInternalFrameSourceImage;
    private javax.swing.JInternalFrame jInternalFrameTargetImage;
    private javax.swing.JInternalFrame jInternalFrameTransformedImage;
    private javax.swing.JLabel jLabelSourceImage;
    private javax.swing.JLabel jLabelTargetImage;
    private javax.swing.JLabel jLabelTransformedImage;
    private javax.swing.JMenuItem jMenuItemStartServer;
    private javax.swing.JMenuItem jMenuItemTransformImages;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBarProgress;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableImageDatabase;
    private javax.swing.JTextPane jTextPaneConsole;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
